global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'flask-instances'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flask1:5000', 'flask2:5000']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
