name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Flask image
        run: docker build -t flask-app .

      - name: Start services
        run: docker-compose up -d

      - name: Wait for services
        run: |
          for i in {1..10}; do
                curl -s http://localhost:8080 && break
                echo "waiting..."
                sleep 5
          done

      - name: Show logs
        if: always()
        run: docker-compose logs

      - name: Test service
        run: curl http://localhost:8080

      - name: Show logs if failed
        if: failure()
        run: docker-compose logs
